const { Dish } = require("./db");

const platos = [
  {
    name: "Plato 1",
    description: "Descripción del plato 1",
    type: "plato principal",
    subtype: "pastas",
    disabled: false,
    available: true,
    calories: 500,
    glutenfree: false,
    vegetarian: false,
    dailyspecial: false,
    price: 1200,
  },
  {
    name: "Plato 2",
    description: "Descripción del plato 2",
    type: "entrada",
    subtype: "ensaladas",
    disabled: false,
    available: true,
    calories: 300,
    glutenfree: true,
    vegetarian: true,
    dailyspecial: false,
    price: 800,
  },
  {
    name: "Plato 21",
    description: "Descripción del plato 21",
    type: "plato principal",
    subtype: "carnes",
    disabled: false,
    available: true,
    calories: 700,
    glutenfree: false,
    vegetarian: false,
    dailyspecial: false,
    price: 1400,
  },
  {
    name: "Plato 22",
    description: "Descripción del plato 22",
    type: "entrada",
    subtype: "pastas",
    disabled: false,
    available: true,
    calories: 400,
    glutenfree: true,
    vegetarian: true,
    dailyspecial: false,
    price: 900,
  },
  {
    name: "Plato 23",
    description: "Descripción del plato 23",
    type: "plato principal",
    subtype: "arroz",
    disabled: false,
    available: true,
    calories: 600,
    glutenfree: false,
    vegetarian: false,
    dailyspecial: false,
    price: 1350,
  },
  {
    name: "Plato 24",
    description: "Descripción del plato 24",
    type: "entrada",
    subtype: "pescados y mariscos",
    disabled: false,
    available: true,
    calories: 350,
    glutenfree: true,
    vegetarian: false,
    dailyspecial: false,
    price: 1050,
  },
  {
    name: "Plato 25",
    description: "Descripción del plato 25",
    type: "plato principal",
    subtype: "sopas",
    disabled: false,
    available: true,
    calories: 250,
    glutenfree: false,
    vegetarian: true,
    dailyspecial: false,
    price: 800,
  },
  {
    name: "Plato 20",
    description: "Descripción del plato 20",
    type: "entrada",
    subtype: "pescados y mariscos",
    disabled: false,
    available: true,
    calories: 300,
    glutenfree: true,
    vegetarian: false,
    dailypecial: false,
    price: 950,
  },
];

const loadplatos = async () => {
  await Dish.bulkCreate(platos);
};

module.exports = loadplatos;
